services:
  api:
    image: golang:1.25-alpine
    container_name: WP_api
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
      - go_cache:/go
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=sistema_WP
      - DB_USER=WP_user
      - DB_PASSWORD=WP_password
      - DB_WAIT_CONNECTIONS=true
      - DB_CONN_LIMIT=10
      - DB_QUEUE_LIMIT=50
      - DB_CONN_TIMEOUT=5000
      - APP_ENV=development
    depends_on:
      - db
    command: >
      sh -c "
      go mod tidy &&
      if ! command -v air >/dev/null; then go install github.com/air-verse/air@latest; fi &&
      air
      "
    restart: unless-stopped

  app:
    image: node:18
    container_name: WP_app
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    tty: true
    ports:
      - "8081:8081"
    command: sh -c "npm install && npm run web"
    environment:
      - NODE_ENV=development
      - EXPO_PUBLIC_API_LOCAL=http://api:3000
      - EXPO_PUBLIC_API_URL=https://api.dominio.com.br
    depends_on:
      - api

  db:
    image: mysql:8.0
    container_name: WP_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sistema_WP
      - MYSQL_USER=WP_user
      - MYSQL_PASSWORD=WP_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    name: WP_db_data
  go_cache:
    name: WP_go_cache